export type BxStatuses =
    "new"
    | "error"
    | "data_send"
    | "china_storage"
    | "shipped_to_russia"
    | "pvz"
    | "pickup"
    | "outwardly"
    | "send_to_russia"
    | "collected"
    | "export"
    | "destruction"
    | "won"