export interface User {
    first_name: string,
    last_name: string,
    patronymic_name: string,
    full_delivery_address: string,
    full_address: string,
    city: string,
    region: string,
    postcode: string,
    email: string,
    passport_series: string,
    passport_number: string,
    passport_issue_date: Date,
    inn: string,
    to_pay_sum: number,
    to_pay_orders: number,
    balance: number,
    subscribe_price: number,
    sub_end: string,
    orders_in_work: number,
    avatar_url: string,
}